### ISSUE TITLE
[BUG] keframes attribute is off by 1

### ISSUE THREAD

**Issue by setop** [CodeMovie/meta#1]
in this [example](https://code.movie/play.html?t=7VjRbtowFP0X7zWrTNJQ6BukpK3aQcWotGqqJidxgoWxmePQ0Yp_n52EQSkUo6KB2iYvjvG95_r42veYJzDGIiWcgVNo6bYkIaINShLVAyQfAQuMUBQRloDTn9DK33sLIEaGSOZ2TyDOWFi0AUYpViZRJspfXQinFqBoomD0WEoYbmfDoPzEDAUUR-A0RjTFFuhzQR45k4h-QyIhLAe1FaCcjHgi0Kg_0WYhp1zoxoAwZQy8znWnq3DHiGZYfX_x8gco6AdMkr5UfYyLIaJqUConFM87pmqQ5APM8oCe45Tue3c3nfNu4-biTplvxLbzR2PHaiY-GhKqnIEhZzwdoVDzszGowvY7ecQ-CqXGq1g5dxelpX3kTstY8rgHePLARWREDsyfZ-QEnEYrqFELTSUWTC3mGF9tA3Fix27dDEKixDDs48C1tw67Z-q-6lRcbOheSkGCTGIjzxXoOi4yS8ZnoTe2hHFwNTKFiXBIkfi3hzd6DyLoVitm9KQqbGbGelCFIQxNg2b5yWGYLTVYNSadEkW6app4rkd2Naqbei7NTCJ2nFplQ8REnYwkp0sdVKZuq-5JzTRcPlI8SG7Gcb0OoW2buiZszEPzhIPQdUPjzBjpGpSZez-G-jX1HvLhEDNp5LkG9Wu6jAu73XsbyNJunEFMi73Oi62e14okk7LcRX11BITlR4l11vI63UbvstP-dX7b67U0Lo_jFMtCAdxPp0Up0jZ9BU6LAFY5uL5st3TJpChVyAujLRCgcJAInrGo0AHRNY71NNIQM10iVU-3nNmsS5tEQmmSOVaz4V2ddTs3YGGjrePM93276RWMxFzg_4sO4azs5gFgIfga1pdIK0buh7Bas-YcCGF8YMSWGrYPqryW7zdrB0JVmKWSDytGfM3G7oO0xbAPhjZ7C9rsT9pmtDlb0OZ80qYFHP4jDUpor_WjZ1RC314d_Tw4CyiHWMwqfDn-tn3W6parWaiBu_wvg-UL_Ex-5OYGl-X5XTQNkbZU99wHEsm-ar1cp90twSHN8nU5sJQAq-XATiq94xwYMQex_F_hkbswUSmyhXmmvzOSJHRiMlfPW5orPKq48-nCV2XOUhaskDm7UjCfCbCH_f-qZFta-3WS7X2S88FSYI38XJkCL-Xn-yTng6XAGim9MgVeSun3Sc4HSQEdzs5Vve8XV46_&p=dVC7bsMwDPwXzh7qFkUafUDXFiiSpclAxIytQJYMikoCGPr3UEZQ9-Fu1D14R41wJo42eDB1BcmCGaEPDbq3gRQ7ootUQRycla2lC5jnhwoGprM-3tGTK4YwaYWTSg-Jmby8MvYEZp2LOpzoIIvqljwxug_lpw7fWbVKRz39IadSWenYIdPi3k765aVqsg25gA2YedRdpxj8_0mSJLBF9yvsi7_fWBix4vRy2PhpaqACh75N2Ba0xChyLN8TwXyOYLVJvdYIuqofai1zB19mcOcfZ3z1A9_5J8j7nG8%3D), there are 3 frames.

But the generated HTML code missed to declare the last one. As a result, it is not displayed.

![Screenshot from 2024-07-01 03-13-48](https://github.com/CodeMovie/meta/assets/7794056/2c8ecf49-3c02-44e7-931a-d7de0f70e864)

**Comment by SirPepe** [comment]
Thank you, fix is deployed!
