### ISSUE TITLE
[request] support more languages

### ISSUE THREAD

**Issue by setop** [CodeMovie/meta#2]
I tried with Elixir code but syntax highlighting is not supported making the result a bit disappointing.

**Comment by SirPepe** [comment]
I should be able to whip up *some* support for elixir somewhat quickly, but I know literally nothing about the language. Expect the first few iterations to suck *a lot* :)

**Comment by setop** [comment]
The language is _really_ nice, just pattern matching and pipe operator are god's gifts. But that's not the topic :)

I don't know the effort for CodeMovie to support a new language. You did not published the generator, only the runtime, did you ?
I looks like it is based on tokens and not depending on the language syntax, is it ?
Elixir is supported by [highlightjs](https://highlightjs.readthedocs.io/en/latest/supported-languages.html), I don't know if it helps.

**Comment by SirPepe** [comment]
It roughly works like this:

1. parse code into a CST using some sort of parser infrastructure (currently mostly [lezer](https://lezer.codemirror.net/))
2. massage the CST to make step 3 work as good as possible
3. apply the default logic to handle diffing, CSS generation etc.

In theory a 10 line wrapper around [lezer-elixir](https://github.com/livebook-dev/lezer-elixir) world add "support" for elixir, but without step 2, it would not be particularly great support. The diffing algorithm works best when the CST is augmented with all sorts of context information, some language-specific magic numbers might need adjusting. Some nodes in the CST even need to be broken down more than any regular parser would normally do (eg. parse natural language inside strings and comments).

We'll see how it goes. I will take a stab at elixir in the next few days.

**Comment by SirPepe** [comment]
Progress report: I worked my way through most of the documentation and should have most syntax working properly. The next step is to extract more context info for the diffing algorithm, but that should not take too long, given what I now know about Elixir and the parse tree. Expect a release (extremely buggy) in a few days.

Screenshot from my test bench:

![Bildschirmfoto vom 2024-07-04 21-49-30](https://github.com/CodeMovie/meta/assets/133494/fa9fa69f-e6b6-4f91-b354-fb23a7433613)

**Comment by SirPepe** [comment]
[This is as far as I got](https://github.com/user-attachments/files/16126929/codemovie-code-movie-0.0.13%2Belixir.zip) without really trying to build some animations (and actually learning elixir in the process). Probably not perfect, but maybe okay for a first release. Expect that in a few days, once the playground and the docs have been updated.

![Bildschirmfoto vom 2024-07-08 13-27-19](https://github.com/CodeMovie/meta/assets/133494/e8d93b93-cb26-46de-ab4b-e5e971934cc9)

**Comment by setop** [comment]
lovely

**Comment by SirPepe** [comment]
https://code.movie/blog/elixir-support-and-improved-stability-in-0.0.14.html :sparkles: 

LMK if you find any bugs, strange behavior, missing syntax etc.

**Comment by setop** [comment]
I tested with a more larger code snippet. It is beautiful :)
