### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by JonnieCache** [CodeMovie/meta#3]
I have a project that I'd love to use code movie for but I need rust support, so consider this a request :)

**Comment by SirPepe** [comment]
On it.

**Comment by SirPepe** [comment]
![Bildschirmfoto vom 2024-07-19 00-24-31](https://github.com/user-attachments/assets/28dab730-426a-492f-8048-ae42e4a22c70)

I can already tell that this will take quite some time 😵‍💫 Stay tuned.

**Comment by SirPepe** [comment]
It moves and looks alright: https://mastodon.social/@sir_pepe/112854537968879507

I still need to work my way through much of the rest of the language, and then there are heuristics to tweak. Would a somewhat/definitely alpha version of rust support help you get your project started? There won't be any crashes (probably), but a lot of syntax won't have highlighting and some animation decisions will be garbage.

**Comment by SirPepe** [comment]
https://code.movie/blog/rust-support-and-improved-code-splitting-in-0.0.17.html :sparkles:
